apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apps.health-samurai.io 
spec:
  group: health-samurai.io
  version: v1
  names:
    kind: App
    plural: apps
  scope: Namespaced
validation:
  openAPIV3Schema:
    properties:
      metadata:
        required:
          - name
        properties:
          name:
            type: string
      domain:
        type: string
      image:
        type: string
      version:
        type: string
      replicas:
        type: integer
        minimum: 1
    required:
      - image
      - version
      - replicas
      - domain

# ---
# apiVersion: apiextensions.k8s.io/v1beta1
# kind: CustomResourceDefinition
# metadata:
#   name: appstatuses.health-samurai.io 
# spec:
#   group: health-samurai.io
#   version: v1
#   names:
#     kind: AppStatus
#     plural: appstatuses
#   scope: Namespaced
